#!/usr/bin/env python
# encoding: utf-8

"""
Usage:
  add-prefix (<filename> | -) <prefix>
  add-prefix (-h | --help)
"""

from __future__ import absolute_import
from __future__ import print_function
import sys
import codecs
from json import dumps
from json import loads
from logging import getLogger, basicConfig, INFO

try:
    from docopt import docopt
except ImportError:
    print('pip install docopt')
    sys.exit(1)

from rss import add_prefix, get_content


logger = getLogger()


def main():
    arguments = docopt(__doc__)

    filename = arguments['<filename>']
    content = get_content(filename)
    if not content:
        logger.info('No content')
        return

    prefix = arguments['<prefix>']

    data = add_prefix(loads(content), prefix)

    sys.stdout = codecs.getwriter('utf-8')(sys.stdout)
    sys.stdout.write(dumps(data, ensure_ascii=False))


if __name__ == '__main__':
    basicConfig(level=INFO)
    main()
