#!/usr/bin/env python
# encoding: utf-8

"""
Usage:
  fetch-feed [--invalidate] [--cache=<cache>] <url>
  fetch-feed (-h | --help)
"""

from __future__ import absolute_import
from __future__ import print_function
import sys
import codecs
from logging import getLogger, basicConfig, INFO

try:
    from docopt import docopt
except ImportError:
    print('pip install docopt')
    sys.exit(1)

from rss import fetch_feed


logger = getLogger()


def main():
    arguments = docopt(__doc__)

    cache = arguments['--cache'] or './.cache'
    invalidate = arguments['--invalidate']
    url = arguments['<url>']

    content = fetch_feed(url, cache, invalidate)

    sys.stdout = codecs.getwriter('utf-8')(sys.stdout)
    sys.stdout.write(content.decode('utf-8'))


if __name__ == '__main__':
    basicConfig(level=INFO)
    main()
